### ISSUE TITLE
Abstract npm scripts into cozy-cli ?

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-template#48]
We now have several apps that share a common set of scripts. This shared logic is difficult to keep coherent between the apps.

Maybe a CLI `cozy` could help with that.

`cozy build`
`cozy deploy`
`cozy watch`

Is there any inconvenient I do not see ?

Sample package.json.scripts

```json
{
    "build": "npm run build:browser",
    "build:browser": "NODE_ENV=browser:production npm run commons:build",
    "build:mobile": "NODE_ENV=mobile:production npm run commons:build",
    "clean:browser": "rm -rf build/*",
    "clean:mobile": "rm -rf mobile/www/*",
    "commons:build": "webpack --config webpack.config.js --bail",
    "commons:watch": "webpack --config webpack.config.js --watch --display-modules --display-chunks",
    "commons:watch:standalone": "webpack-dev-server --config webpack.config.js --display-modules --display-chunks --inline --hot",
    "deploy": "git-directory-deploy --username Cozy --email contact@cozycloud.cc --directory build/ --repo=https://$GITHUB_TOKEN@github.com/<USERNAME_GH>/<SLUG_GH>.git",
    "tx": "tx pull --all || true",
    "precommons:build": "npm-run-all lint tx",
    "prebuild:browser": "npm run clean:browser",
    "prebuild:mobile": "npm run clean:mobile",
    "pretest": "npm run lint",
    "prewatch:browser": "npm run clean:browser",
    "prewatch:mobile": "npm run clean:mobile",
    "lint": "npm-run-all --parallel 'lint:*'",
    "lint:js": "eslint 'src/**/*.js' 'src/**/*.jsx' 'test/**/*.js' 'mobile/src/**/*.js' 'mobile/src/**/*.jsx' 'mobile/test/**/*.js'",
    "lint:styles": "stylint src/styles --config ./.stylintrc",
    "stack:docker": "docker run --rm -it -p 8080:8080 -v \"$(pwd)/build\":/data/cozy-app/app cozy/cozy-app-dev",
    "test": "node --harmony_proxies node_modules/.bin/jest",
    "watch": "npm run watch:browser",
    "watch:browser": "NODE_ENV=browser:development npm run commons:watch",
    "watch:mobile": "NODE_ENV=mobile:development npm run commons:watch",
    "watch:browser:standalone": "NODE_ENV=browser:development npm run commons:watch:standalone",
    "watch:mobile:standalone": "NODE_ENV=mobile:development npm run commons:watch:standalone",
    "watch:standalone": "npm run watch:browser:standalone",
    "android:run": "cd mobile ; cordova run android --device ; cd ..",
    "android:run:emulator": "cd mobile ; cordova run android --emulator ; cd ..",
    "android:release": "npm run build:mobile && cd mobile ; cordova build android --release ; cd ..",
    "android:signed": "npm run android:release && cd mobile ; apksigner sign --ks keys/android/<APP_NAME>-release-key.jks --out build/android/<APP_NAME>.apk platforms/android/build/outputs/apk/android-release-unsigned.apk ; cd ..",
    "android:publish": "npm run android:signed && cd mobile ; fastlane supply ; cd ..",
    "ios:run": "cd mobile ; cordova run ios --device ; cd ..",
    "ios:run:emulator": "cd mobile ; cordova run ios --emulator ; cd .."
}
```

**Comment by GoOz** [comment]
Not sure I understand the need, honestly.

**Comment by ptbrowne** [comment]
There is a fair amount of logic in the `package.json` and this logic has to be duplicated across projects. When we want to make a change (adding hot-reload for example), it is difficult to do this across every app in 1 go.

Since `cozy` is meant to be a platform where developers would build apps, it would be good if evolution in developer tools could be easy to share. This is why I was thinking that a dedicated tool could be in a separate repository. It would initially contain the commands listed in the package.json (see above) so that we can do `cozy run`, `cozy build` etc...

Then if we make an improvement, the developer could just do `yarn update cozy-cli` and be good to go.

**Comment by GoOz** [comment]
Not sure really that it's gonna make things a lot easier but I suppose this should be discussed with everyone also.

**Comment by y-lohse** [comment]
Here are the downsides I see:

- Our CI tools use these commands, so they'll still need to be accessible somehow.
- The logic in the command is strongly coupled with the repo's set-up (mostly the webpack configuration), so keeping them in the same place is actually a good thing. It also allows for flexibility of it's needed.

They aren't major downsides, but I don't feel like the upsides are major either. We rarely have critical things to change in these commands so it can just be done over time or on friday afternoons.

**Comment by enguerran** [comment]
I suggest `cozy-template` is the source of truth for scripts and configurations, and whenever you want to use something in your own project, you copy/paste from `cozy-template`.

However some could create a `cozy-cli` on his/her own and see if it responds to the 3 U : useful, usable and used. Maintain another project sounds we become a labyrinthine system.

**Comment by ptbrowne** [comment]
> Our CI tools use these commands, so they'll still need to be accessible somehow.

When installing the dependencies of the project, it will have access to the CLI.

> However some could create a cozy-cli on his/her own and see if it responds to the 3 U : useful, usable and used. Maintain another project sounds we become a labyrinthine system.

I think it is good way to move forward indeed. Thanks for you answers !
